language: cpp

compiler:
    - gcc

sudo: false

addons:
  apt:
    packages:
      - libboost-dev
      - doxygen
      - g++-5
      - libgtest-dev
      - valgrind
    sources:
      - ubuntu-toolchain-r-test

install:
    - pwd
    - ls -al
    - mkdir gtest
    - cd gtest
    - pwd
    - ls -al
    - export LIBRARY_PATH=$(pwd)
    - cp -r /usr/src/gtest/* ./
    - cmake -D CMAKE_INSTALL_PREFIX:PATH=./ ./
    - make
    - pwd
    - ls -al
    - cd -

before_script:
    - uname -a
    - printenv
    - grep "#define BOOST_VERSION " /usr/include/boost/version.hpp
    - dpkg -l libgtest-dev
    - make versions

script:
    - date
    - ls -al
    - make test
